name: Python package

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write


jobs:

  test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest bottle
      - name: Test pytest
        run: pytest


  deployment:
    needs: test
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: echo mep
        run: echo "MEP"
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Test if website is up 🚀
        run: |
          pip install requests
          python -c "import requests; exit(1) if requests.get('https://www.google.fr').status_code != 200 else exit(0)"
  notification:
    if: success() || failure()
    needs: deployment

    runs-on: ubuntu-latest
    steps:
      - name: notif
        run: echo ${{job.status}}