name: Python package

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Lint with black
        run: |
          black . --check

  test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest bottle
      - name: Test pytest
        run: pytest


  coverage:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage-badge
      - name: Test pytest + coverage
        run: pytest --cov=. . --cov-report html:cov-html
      - name: Badge
        run: coverage-badge -o ./cov-html/cov.svg -f
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './cov-html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1


  deployment:
    needs: test
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: echo mep
        run: echo "MEP"
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Test if website is up 🚀
        run: |
          pip install requests
          python -c "import requests; exit(1) if requests.get('https://www.google.fr').status_code != 200 else exit(0)"
  notification:
    if: success() || failure()
    needs: deployment

    runs-on: ubuntu-latest
    steps:
      - name: notif
        run: echo ${{job.status}}